-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.badges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  category character varying,
  tier character varying CHECK (tier::text = ANY (ARRAY['Bronze'::character varying, 'Silver'::character varying, 'Gold'::character varying, 'Platinum'::character varying, 'Diamond'::character varying]::text[])),
  icon_url text,
  color character varying,
  criteria_type character varying,
  criteria_value integer,
  criteria_config jsonb,
  rarity_score integer DEFAULT 1,
  auto_award boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT badges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.certifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  subtitle character varying,
  description text,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['AI'::character varying, 'Cybersecurity'::character varying, 'Cloud'::character varying]::text[])),
  level character varying CHECK (level::text = ANY (ARRAY['Foundation'::character varying, 'Associate'::character varying, 'Professional'::character varying, 'Expert'::character varying]::text[])),
  provider character varying,
  estimated_duration_hours integer,
  prerequisites ARRAY,
  icon_url text,
  badge_url text,
  overview text,
  study_resources jsonb,
  official_url text,
  exam_code character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT certifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  short_description character varying,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['AI'::character varying, 'Cybersecurity'::character varying, 'Cloud'::character varying]::text[])),
  difficulty character varying NOT NULL CHECK (difficulty::text = ANY (ARRAY['Beginner'::character varying, 'Intermediate'::character varying, 'Advanced'::character varying, 'Expert'::character varying]::text[])),
  duration_hours integer,
  thumbnail_url text,
  cover_image_url text,
  prerequisites ARRAY,
  learning_objectives ARRAY,
  enrolled_count integer DEFAULT 0,
  completion_count integer DEFAULT 0,
  average_rating numeric DEFAULT 0.0,
  is_published boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT courses_pkey PRIMARY KEY (id),
  CONSTRAINT courses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.daily_activities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  activity_date date NOT NULL,
  activities_completed integer DEFAULT 0,
  xp_earned integer DEFAULT 0,
  lessons_completed integer DEFAULT 0,
  exercises_completed integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_activities_pkey PRIMARY KEY (id),
  CONSTRAINT daily_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.enrollments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  course_id uuid NOT NULL,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'dropped'::character varying, 'paused'::character varying]::text[])),
  progress_percentage integer DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
  current_lesson_id uuid,
  completed_at timestamp with time zone,
  last_accessed_at timestamp with time zone,
  enrolled_at timestamp with time zone DEFAULT now(),
  CONSTRAINT enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT enrollments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id),
  CONSTRAINT enrollments_current_lesson_id_fkey FOREIGN KEY (current_lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.lesson_progress (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  lesson_id uuid NOT NULL,
  enrollment_id uuid NOT NULL,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  started_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lesson_progress_pkey PRIMARY KEY (id),
  CONSTRAINT lesson_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT lesson_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id),
  CONSTRAINT lesson_progress_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES public.enrollments(id)
);
CREATE TABLE public.lessons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  course_id uuid NOT NULL,
  title character varying NOT NULL,
  slug character varying NOT NULL,
  description text,
  content_type character varying NOT NULL CHECK (content_type::text = ANY (ARRAY['video'::character varying, 'text'::character varying, 'quiz'::character varying]::text[])),
  video_url text,
  video_duration_minutes integer,
  text_content text,
  quiz_id uuid,
  order_index integer NOT NULL,
  module_name character varying,
  xp_reward integer DEFAULT 10,
  is_published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lessons_pkey PRIMARY KEY (id),
  CONSTRAINT lessons_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id),
  CONSTRAINT lessons_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type character varying NOT NULL,
  title character varying NOT NULL,
  message text,
  action_url text,
  action_label character varying,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.practice_attempts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  attempt_number integer DEFAULT 1,
  answers jsonb,
  score integer,
  passed boolean,
  xp_earned integer DEFAULT 0,
  is_best_score boolean DEFAULT false,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  time_taken_minutes integer,
  CONSTRAINT practice_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT practice_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT practice_attempts_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.practice_exercises(id)
);
CREATE TABLE public.practice_exercises (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['AI'::character varying, 'Cybersecurity'::character varying, 'Cloud'::character varying]::text[])),
  difficulty character varying CHECK (difficulty::text = ANY (ARRAY['Beginner'::character varying, 'Intermediate'::character varying, 'Advanced'::character varying, 'Expert'::character varying]::text[])),
  questions jsonb NOT NULL,
  passing_score integer DEFAULT 70,
  time_limit_minutes integer,
  xp_reward integer DEFAULT 15,
  thumbnail_url text,
  related_course_ids ARRAY,
  tags ARRAY,
  is_published boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT practice_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT practice_exercises_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  username character varying NOT NULL UNIQUE,
  full_name character varying,
  email character varying NOT NULL UNIQUE,
  bio text,
  avatar_url text,
  cover_image_url text,
  role character varying DEFAULT 'user'::character varying CHECK (role::text = ANY (ARRAY['user'::character varying, 'admin'::character varying]::text[])),
  total_xp integer DEFAULT 0,
  level integer DEFAULT 1,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  last_activity_date date,
  followers_count integer DEFAULT 0,
  following_count integer DEFAULT 0,
  is_public boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.quiz_attempts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  quiz_id uuid NOT NULL,
  lesson_id uuid,
  attempt_number integer DEFAULT 1,
  answers jsonb,
  score integer,
  passed boolean,
  xp_earned integer DEFAULT 0,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  time_taken_minutes integer,
  CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT quiz_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT quiz_attempts_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id),
  CONSTRAINT quiz_attempts_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(id)
);
CREATE TABLE public.quizzes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  description text,
  passing_score integer DEFAULT 70,
  time_limit_minutes integer,
  max_attempts integer,
  questions jsonb NOT NULL,
  xp_reward integer DEFAULT 20,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quizzes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_badges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  badge_id uuid NOT NULL,
  earned_at timestamp with time zone DEFAULT now(),
  awarded_by uuid,
  is_displayed boolean DEFAULT true,
  CONSTRAINT user_badges_pkey PRIMARY KEY (id),
  CONSTRAINT user_badges_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_badges_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES public.badges(id),
  CONSTRAINT user_badges_awarded_by_fkey FOREIGN KEY (awarded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_certifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  certification_id uuid NOT NULL,
  status character varying DEFAULT 'in_progress'::character varying CHECK (status::text = ANY (ARRAY['in_progress'::character varying, 'completed'::character varying]::text[])),
  resources_completed jsonb DEFAULT '[]'::jsonb,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  passed_real_exam boolean DEFAULT false,
  exam_passed_date date,
  certificate_number character varying,
  is_pinned boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_certifications_pkey PRIMARY KEY (id),
  CONSTRAINT user_certifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_certifications_certification_id_fkey FOREIGN KEY (certification_id) REFERENCES public.certifications(id)
);
CREATE TABLE public.xp_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  amount integer NOT NULL,
  source_type character varying NOT NULL,
  source_id uuid,
  description character varying,
  awarded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT xp_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT xp_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT xp_transactions_awarded_by_fkey FOREIGN KEY (awarded_by) REFERENCES public.profiles(id)
);
