-- ============================================
-- Seed Data: Certifications
-- ============================================
-- Populates certifications based on data from certification.html and script.js

INSERT INTO certifications (slug, title, subtitle, description, category, level, provider, icon_url, badge_url, overview, estimated_duration_hours, prerequisites, official_url, exam_code, is_active) VALUES

-- Cloud Certifications
('aws-certified-solutions-architect',
 'AWS Certified Solutions Architect',
 'Associate Level',
 'Validate your ability to design and deploy scalable, highly available systems on AWS. This certification demonstrates expertise in architecting distributed systems on the AWS platform.',
 'Cloud', 'Associate', 'Amazon Web Services',
 '/images/home/cert-aws.png',
 '/images/certifications/aws-saa-badge.png',
 'The AWS Certified Solutions Architect - Associate exam validates the ability to design distributed applications and systems on the AWS platform. It tests knowledge of AWS services, architecture best practices, and security.',
 180,
 ARRAY['6 months of AWS experience', 'Understanding of basic architecture'],
 'https://aws.amazon.com/certification/certified-solutions-architect-associate/',
 'SAA-C03',
 true),

('aws-cloud-practitioner',
 'AWS Certified Cloud Practitioner',
 'Foundation Level',
 'Foundational understanding of AWS Cloud concepts, services, and terminology. Perfect for individuals new to AWS or cloud computing.',
 'Cloud', 'Foundation', 'Amazon Web Services',
 '/images/certifications/aws-ccp-icon.png',
 '/images/certifications/aws-ccp-badge.png',
 'Entry-level certification that validates overall understanding of the AWS Cloud. Covers cloud concepts, AWS services, security, architecture, pricing, and support.',
 80,
 ARRAY['Basic IT knowledge', 'Understanding of cloud concepts'],
 'https://aws.amazon.com/certification/certified-cloud-practitioner/',
 'CLF-C02',
 true),

('azure-administrator',
 'Microsoft Azure Administrator',
 'Associate Level',
 'Demonstrate skills in implementing, managing, and monitoring Azure environments. Essential for IT professionals managing cloud infrastructure.',
 'Cloud', 'Associate', 'Microsoft',
 '/images/certifications/azure-admin.png',
 '/images/certifications/azure-admin-badge.png',
 'This certification validates skills in implementing, monitoring, and maintaining Microsoft Azure solutions. Covers compute, storage, network, and security services.',
 150,
 ARRAY['Understanding of Azure services', 'Basic PowerShell knowledge'],
 'https://learn.microsoft.com/en-us/certifications/azure-administrator/',
 'AZ-104',
 true),

('google-cloud-architect',
 'Google Cloud Professional Architect',
 'Professional Level',
 'Design, develop, and manage robust, secure, scalable, and dynamic solutions on Google Cloud Platform.',
 'Cloud', 'Professional', 'Google Cloud',
 '/images/certifications/gcp-architect.png',
 '/images/certifications/gcp-architect-badge.png',
 'This certification demonstrates ability to design, plan, and architect Google Cloud solutions that meet business and technical requirements.',
 200,
 ARRAY['3+ years industry experience', '1+ year GCP experience', 'Understanding of cloud architecture'],
 'https://cloud.google.com/certification/cloud-architect',
 'PROFESSIONAL-CLOUD-ARCHITECT',
 true),

-- Cybersecurity Certifications
('cissp',
 'Certified Information Systems Security Professional',
 'CISSP',
 'Globally recognized certification demonstrating expertise in designing, implementing, and managing cybersecurity programs.',
 'Cybersecurity', 'Professional', 'ISC²',
 '/images/home/cert-cissp.png',
 '/images/certifications/cissp-badge.png',
 'CISSP is one of the most prestigious certifications in cybersecurity. It covers eight domains including security and risk management, asset security, security architecture, and more.',
 400,
 ARRAY['5 years paid work experience in 2+ CISSP domains', 'Bachelor degree or additional credential (reduces experience to 4 years)'],
 'https://www.isc2.org/Certifications/CISSP',
 'CISSP',
 true),

('comptia-security-plus',
 'CompTIA Security+',
 'Foundation Level',
 'Establish the core knowledge required of any cybersecurity role and provides a springboard to intermediate-level cybersecurity jobs.',
 'Cybersecurity', 'Foundation', 'CompTIA',
 '/images/certifications/security-plus.png',
 '/images/certifications/security-plus-badge.png',
 'CompTIA Security+ is a global certification that validates the baseline skills necessary to perform core security functions and pursue an IT security career.',
 120,
 ARRAY['2 years IT administration experience with security focus', 'CompTIA Network+ recommended'],
 'https://www.comptia.org/certifications/security',
 'SY0-701',
 true),

('ceh',
 'Certified Ethical Hacker',
 'v12',
 'Learn to think like a hacker to better defend against attacks. Master ethical hacking tools and techniques.',
 'Cybersecurity', 'Professional', 'EC-Council',
 '/images/certifications/ceh.png',
 '/images/certifications/ceh-badge.png',
 'CEH certification validates skills in ethical hacking and penetration testing. Learn to identify vulnerabilities and weaknesses in target systems using same tools as malicious hackers.',
 250,
 ARRAY['2 years information security experience', 'Networking and system administration knowledge'],
 'https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/',
 'CEH-v12',
 true),

-- AI/Data Certifications
('tensorflow-certificate',
 'TensorFlow Developer Certificate',
 'Professional Level',
 'Demonstrate ML proficiency using TensorFlow to solve deep learning and ML problems.',
 'AI', 'Professional', 'Google',
 '/images/certifications/tensorflow.png',
 '/images/certifications/tensorflow-badge.png',
 'This certification tests your foundational knowledge of integrating machine learning into tools and applications. Covers building TensorFlow models, image classification, NLP, and time series.',
 180,
 ARRAY['Understanding of ML fundamentals', 'Python programming', 'Basic TensorFlow knowledge'],
 'https://www.tensorflow.org/certificate',
 'TENSORFLOW-CERTIFICATE',
 true),

('aws-machine-learning',
 'AWS Certified Machine Learning - Specialty',
 'Specialty Level',
 'Validate ability to design, implement, deploy, and maintain machine learning solutions for given business problems on AWS.',
 'AI', 'Professional', 'Amazon Web Services',
 '/images/certifications/aws-ml.png',
 '/images/certifications/aws-ml-badge.png',
 'This certification validates expertise in building, training, tuning, and deploying ML models using AWS Cloud. Covers data engineering, exploratory data analysis, modeling, and ML implementation.',
 300,
 ARRAY['1-2 years AWS ML workloads experience', 'Understanding of ML algorithms', 'Data engineering skills'],
 'https://aws.amazon.com/certification/certified-machine-learning-specialty/',
 'MLS-C01',
 true);

-- Verify insertion
SELECT slug, title, category, level, provider FROM certifications ORDER BY category, level;
